version: '3'

services:
  web_local:
    image: web_local:latest
    build: .
    command: python project/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: