version: '3'

services:
  web_prod:
    image: web_prod:latest
    build: .
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: